remove rpp data source
DEFRA/fcp-data-access-layer-api pull request #91
Opened 2024-10-25 08:13 UTC by csaltmountain

2024-10-29 10:59 UTC, rkdefra requested changes
A couple of minor changes...

2024-11-08 11:08 UTC, defra-dom approved these changes

2024-11-08 11:08 UTC, defra-dom commented on mocks/collections.js
> -    id: 'release-1',
is it still not useful to have only realease-1 endpoints?

2024-11-08 11:11 UTC, rkdefra approved these changes
LGTM

2024-11-08 11:23 UTC, merged